name: CI

on:
  push:
    branches: [ main_dev ]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Start MongoDB v3.6
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 3.6

      - name: Run build
        run: go build .

      - name: Run vet & lint
        run: |
          go vet .

      - name: Run tests
        run: go test -v ./...
